import './coordinate.js';
import './create-offer.js';
import './create-offer-list.js';
// import { sameOfferList } from './create-offer-list.js';
import './data.js';
import './generation-form.js';
import './util.js';
// import {generateForm} from './generation-form.js';
import './form-validity.js';
import './map.js';
